#!/bin/sh

case "$1" in
  start)
        # Enable lvdspll
        devmem 0xFFFFFC1C w 0x3f0003
        devmem 0xFFFFFC18 w 0x12023010
        devmem 0xFFFFFC10 w 0x1E000000
        devmem 0xFFFFFC1C w 0x20103
        devmem 0xFFFFFC0C w 0xb0000001
        devmem 0xFFFFFC1C w 0x20103
        
        # Enable LVDSC clock
        devmem 0xFFFFFCA4
        devmem 0xFFFFFC88 w 0x90000038
        devmem 0xFFFFFCA4
        
        # Configure LVDSC
        devmem 0xF806000C
        devmem 0xF8060004 w 0x00
        devmem 0xF8060008 w 0x00
        devmem 0xF8060014 w 0x0000008B
        devmem 0xF8060000 w 0x1
        
        # Configure LCDC clock
        devmem 0xF8038000 w 0x2
        ;;
  stop)
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

